spring:
    application:
        name: order-service
    datasource:
        url: jdbc:postgresql://localhost:5432/online_shop
        username: user
        password: root
server:
    port: 8082
product:
    service:
        url: http://localhost:8081